// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"sakata-server-rest/internal/app/handler"
	"sakata-server-rest/internal/app/repository"
	"sakata-server-rest/internal/app/service"
)

// Injectors from wire.go:

// InitializeUserHandler は DI を適用した UserHandler を作成
func InitializeUserHandler() *handler.UserHandler {
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	return userHandler
}

// InitializeThemeHandler は DI で ThemeHandler を生成
func InitializeThemeHandler() *handler.ThemeHandler {
	themeRepository := repository.NewThemeRepository()
	themeService := service.NewThemeService(themeRepository)
	themeHandler := handler.NewThemeHandler(themeService)
	return themeHandler
}

func InitializeGameHandler() *handler.GameHandler {
	db := repository.NewDB()
	gameRepository := repository.NewGameRepository(db)
	gameService := service.NewGameService(gameRepository)
	gameHandler := handler.NewGameHandler(gameService)
	return gameHandler
}
